
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: adilet.2005
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

app:
  security:
    jwt:
      secret_key: java15java
      expiration: 3600

logging:
  level:
    org:springframework.security: DEBUG