
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: adilet.2005
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true

#  web:
#    resources:
#      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/

server:
  port: 8081

app:
  security:
    jwt:
      secret_key: java15java
      expiration: 3600

#logging:
#  level:
#    org:springframework.security: DEBUG
#debug: true

#springdoc:
#  api-docs:
#    enabled: false
#  swagger-ui:
#    csrf:
#      enabled: true
#
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#  api-docs:
#    path: /v3/api-docs
